config/routes.rb
Rails.application.routes.draw do
  
  resources :categories 
  resources :posts
  
	
	resources :activities	
	
  devise_for :doctors, controllers: {registrations: "doctors/registrations"}
  devise_for :patients

  root 'categories#index'
	get 'patient_accounts/:pin' => 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

	belongs_to :patient
	belongs_to :doctor
	belongs_to :hospital

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts
	validates_presence_of :name

end

app/models/city.rb
class City < ActiveRecord::Base
	
	has_many :doctors
	has_many :patients
	has_many :hospitals 	
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  
  enum role: [:author, :super_doctor]
  has_many :activities
  belongs_to :city
  belongs_to :hospital
  
end

app/models/examination.rb
class Examination < ActiveRecord::Base
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	
	belongs_to :city
	has_many :doctors
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
  belongs_to :city


end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :category
	validates_presence_of :category_id, :body, :title
	
	

end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base
		#before_action :authenticate_doctor!
		#before_action :authenticate_patient!, only: [:index, :show] 
		
  def index	
		@activities = current_patient.activities || current_doctor.activities 
	end
	
	def show
		#@activity = @activities.find(params[:id])
	end
	
	def new
	end
	
	def create
	end
	
	def edit
	end
	
	def update
	end
	
	private
	
		def curses
			if doctor_signed_in?
				@curses = current_doctor
			elsif patient_signed_in?
				@curses = current_patient
			else
				redirect_to root_path
			end
		end
		
    def activity_params
      params.require(:activity).permit(:examination_id, :doctor_id, :patient_id, :notes, :attachments, :hospital_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected
  
def after_sign_in_path_for(resource)
  case resource
    when Patient then "/patient_accounts/" + current_patient.pin.to_s
    when Doctor  then stored_location_for(:doctors)
    
  end
end

  def configure_devise_permitted_parameters
    registration_params =[:pin, :first_name, :last_name, :dob, :marital_status, :mobile, :phone, :gender, :city_id, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  
  
  
  
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  	@posts_for_category_listing = @category.posts
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :slug)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
end

app/controllers/doctors/registrations_controller.rb
class Doctors::RegistrationController < Devise::RegistrationsController

	skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
	
	prepend_before_action :authenticate_super_doctor!, only: [:new, :create, :cancel]

	
	protected
	
		def sign_up(resource_name, resource)
		end
		
		def authenticate_super_doctor!
			authenticate_scope!
		
			unless resource.super_doctor?
				redirect_to  root_path
			end
		
		end	
	
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  	@post.view+=1
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :slug, :image, :body, :view, :category_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<script>
$(document).ready(function(){
    $(".hide").click(function(){
        $(this).parent("p").next("div").hide();
    });
    $(".show").click(function(){
        $(this).parent("p").next("div").show();
    });
});
</script>

<h1>Müayinələr</h1>
<hr>
    <% @activities.each do |act| %>

<p>Müayinə kodu: <%= Examination.find(act.examination_id).shortname%><%= "#{act.id}#{act.doctor_id}#{act.patient_id}#{act.created_at.to_s[0..9]}".split("-").join %>  <button class="hide">Bağla</button>
<button class="show">Göstər</button></p>

<div>
<p>Müayinə elədi: <%= act.doctor.first_name %> <%= act.doctor.last_name %>
<p>Müayinə olundu: <%= act.patient.first_name %> <%= act.patient.last_name %>
<p>Xəstəxana: <%= act.hospital.name %> (<%= act.hospital.city.name %>)
<p>Qeydlər: <%= act.notes %>
<% if act.attachments %>
<p>Əlavə: <%= act.attachments.split.length %> şəkil <div><%= image_tag(act.attachments)%></div>
<% end %>
<p>Tarix: <%= act.created_at.to_s[0..9]%>  Saat: <%= act.created_at.to_s[11..18]%>
</div>
<hr>

      <% if current_doctor %>
        <%= link_to 'Edit', edit_activity_path(activity) %>
      <% end %>

    <% end %>

<br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>


<% @activities.each do |act| %>

<p>Müayinə elədi: <%= act.doctor.first_name %><%= act.doctor.last_name %>
<p>Müayinə olundu: <%= act.patient.first_name %><%= act.patient.last_name %>
<p>XəstƏxana: <%= act.hospital.name %> (<%= act.hospital.city.name %>)
<p>Qeydlər: <%= act.notes %>
<% if attachments %>
<p>Əlavə: <%= act.attachments %>
<% end %>
<p>Tarix: <%= act.created_at.to_s[0..9]%>  Saat: <%= act.created_at.to_s[11..18]%>
<% if current_doctor %>
<%= link_to 'Edit', edit_activity_path(@activity) %> |
<% end %>

<%= link_to 'Back', activities_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.slug %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

		<ul>
					<% @posts_for_category_listing.each do |p| %>
          <li><%= link_to p.title, p %><span><%= p.view %></span></li>
          <hr>
          <% end %>
		</ul>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Body</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.slug %></td>
        <td><%= post.body %></td>
        <td><%= post.category_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@post.image, alt: @post.title) %>
</p>


<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<p><%= @post.view %> dəfə oxunulub</p>
<p>
  <strong>Category:</strong>
  <%= link_to @post.category[:name], category_path(@post.category[:id]) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>